/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Employee;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EmployControllerApi
 */
@Disabled
public class EmployControllerApiTest {

    private final EmployControllerApi api = new EmployControllerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createEmpTest() throws ApiException {
        Employee employee = null;
        String response = api.createEmp(employee);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteEmpTest() throws ApiException {
        Long id = null;
        String response = api.deleteEmp(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void showEmpTest() throws ApiException {
        List<Employee> response = api.showEmp();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateEmpTest() throws ApiException {
        Long id = null;
        Employee employee = null;
        String response = api.updateEmp(id, employee);
        // TODO: test validations
    }

}
